"""
Email Notification Service
──────────────────────────
Sends transactional emails via SendGrid when audits complete.
"""
import logging
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from app.config import settings

logger = logging.getLogger(__name__)


def send_audit_complete_email(
    shop_domain: str,
    shop_email: str,
    audit_id: str,
    overall_score: float,
    critical_count: int,
    warning_count: int,
) -> bool:
    """Send email notification when an audit completes."""

    if not shop_email:
        logger.warning(f"No email for shop {shop_domain}, skipping notification")
        return False

    if not settings.SENDGRID_API_KEY:
        logger.warning("SENDGRID_API_KEY not configured, skipping email")
        return False

    # Determine score status
    if overall_score >= 70:
        status_text = "Great"
        color = "#10b981"
        emoji = "🎉"
    elif overall_score >= 40:
        status_text = "Good"
        color = "#f59e0b"
        emoji = "👍"
    else:
        status_text = "Needs Improvement"
        color = "#ef4444"
        emoji = "⚠️"

    subject = f"{emoji} Your ShopIQ Audit is Complete — Score: {overall_score:.1f}/100"

    html_body = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background: #f3f4f6; }}
    .container {{ max-width: 600px; margin: 40px auto; }}
    .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 36px 30px; text-align: center; border-radius: 10px 10px 0 0; }}
    .header h1 {{ margin: 0 0 8px; font-size: 24px; font-weight: 700; }}
    .header p {{ margin: 0; opacity: 0.85; font-size: 14px; }}
    .content {{ background: #ffffff; padding: 36px 30px; border-radius: 0 0 10px 10px; }}
    .score-block {{ text-align: center; margin: 0 0 32px; padding-bottom: 28px; border-bottom: 1px solid #f1f5f9; }}
    .score {{ font-size: 60px; font-weight: 700; color: {color}; line-height: 1; display: block; }}
    .score-max {{ font-size: 20px; color: #94a3b8; font-weight: 400; }}
    .status {{ color: {color}; font-size: 18px; font-weight: 600; margin: 10px 0 0; display: block; }}
    .metrics {{ display: table; width: 100%; margin: 0 0 32px; }}
    .metric {{ display: table-cell; text-align: center; padding: 8px; }}
    .metric-val {{ font-size: 40px; font-weight: 700; display: block; }}
    .metric-label {{ color: #6b7280; font-size: 13px; margin-top: 4px; display: block; }}
    .btn {{ display: inline-block; background: #667eea; color: #ffffff; padding: 14px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; font-size: 15px; }}
    .footer {{ color: #9ca3af; font-size: 12px; text-align: center; margin-top: 24px; }}
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🚀 ShopIQ Audit Complete</h1>
      <p>{shop_domain}</p>
    </div>
    <div class="content">
      <div class="score-block">
        <span class="score">{overall_score:.1f}<span class="score-max">/100</span></span>
        <span class="status">{status_text}</span>
      </div>
      <div class="metrics">
        <div class="metric">
          <span class="metric-val" style="color: #ef4444;">{critical_count}</span>
          <span class="metric-label">Critical Issues</span>
        </div>
        <div class="metric">
          <span class="metric-val" style="color: #f59e0b;">{warning_count}</span>
          <span class="metric-label">Warnings</span>
        </div>
      </div>
      <div style="text-align: center;">
        <a href="{settings.FRONTEND_URL}/dashboard" class="btn">View Full Report →</a>
      </div>
      <p class="footer">
        This report was automatically generated by ShopIQ.<br>
        You're receiving this because your store {shop_domain} is connected.
      </p>
    </div>
  </div>
</body>
</html>"""

    try:
        message = Mail(
            from_email=settings.FROM_EMAIL,
            to_emails=shop_email,
            subject=subject,
            html_content=html_body,
        )
        sg = SendGridAPIClient(settings.SENDGRID_API_KEY)
        response = sg.send(message)
        logger.info(f"✅ Audit email sent to {shop_email} (status {response.status_code})")
        return True
    except Exception as e:
        logger.error(f"❌ Failed to send audit email to {shop_email}: {e}")
        return False
